backend = "glx";
vsync = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = true;

# Opacity
inactive-opacity = 0.92;
active-opacity = 1.0;
frame-opacity = 1.0;

# Fading
fading = true;
fade-in-step = 0.07;
fade-out-step = 0.07;

# Shadows
shadow = true;
shadow-radius = 12;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.6;

# Corners
corner-radius = 8;

# Exclude
shadow-exclude = [
    "class_g = 'i3-frame'"
];
